## nginx_ingress_gRPC_rules.yaml

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
  name: nginx-ingress-grpc
  namespace: kube-system
spec:
  tls:
  - hosts:
    - delivery.gship.com
    secretName: delivery-secret
  rules:
  - host: delivery.gship.com
    http:
      paths:
      - path: /Carrier/GetCarrier
        backend:
          serviceName: carrier
          servicePort: 50052
      - path: /Shipment/GetShipment
        backend:
          serviceName: shipment
          servicePort: 50051
      - path: /Shipment/GetCarrierForShipment
        backend:
          serviceName: shipment
          servicePort: 50051
